# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=3000
spring.data.redis.password=1234
# Server
server.port=8080
server.shutdown=graceful
spring.application.name=bunny
# DB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.show-sql=true
spring.jpa.properties.properties.hibernate.format_sql=true
spring.jpa.properties.use_sql_comments=true
spring.jpa.open-in-view=false
# AWS S3 ?? ??
cloud.aws.s3.bucketName=bunny-bunny-bunny123
cloud.aws.credentials.accessKey=${S3_ACCESSKEY}
cloud.aws.credentials.secretKey=${S3_SECRETKEY}
cloud.aws.region.static=ap-southeast-2
cloud.aws.stack.auto=false
# jwt.secret
jwt.secret=my-secret-key-jwt-secret-key-example-bunny
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=1209600000